name: CD
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  helm-publish:
    name: Helm Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Publish Helm Chart
        run: bash scripts/ci/helm-publish.sh
