name: CD
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  docker-push:
    name: Docker Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Push Docker Image
        run: bash scripts/ci/docker-push.sh
