name: CD
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  docker:
    name: Docker Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      image_name: let__platform__-let__service__
      dockerfile: ./infra/Dockerfile
      version: ${{ github.ref_name }}
