name: CD
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  docker-cd:
    name: Docker CD
    permissions:
      contents: read
      packages: write
    runs-on:
      - nscloud-ubuntu-22.04-amd64-32x64-with-cache
      - nscloud-cache-size-50gb
    strategy:
      matrix:
        image:
          - name: let__platform__-let__service__
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Namespace
        uses: namespacelabs/nscloud-setup@v0
      - name: Setup Namespace buildx
        uses: namespacelabs/nscloud-setup-buildx-action@v0
      - name: Re-tag commit image to release
        env:
          DOMAIN: ghcr.io
          GITHUB_REPO_REF: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          LATEST_BRANCH: main
          CI_DOCKER_IMAGE: ${{ matrix.image.name }}
        run: ./scripts/ci/cd-docker.sh "${{ github.ref_name }}"
