name: CI
on:
  push:
jobs:
  docker:
    name: Docker Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      image_name: let__platform__-let__service__
      dockerfile: ./infra/Dockerfile
